source 'https://rubygems.org'

gem 'builder', '~> 3.2.2'
gem 'jasmine', '~> 2.2.0'
gem 'middleman', '~>3.3.10'
gem 'middleman-sitemap'
gem 'middleman-blog'
gem 'middleman-syntax', '~> 2.0.0'
gem 'middleman-autoprefixer', '~> 2.4.3'
gem 'middleman-minify-html', '~> 3.4.0'
gem 'redcarpet', '~> 3.2.3'
